---
title: "Regression Project"
authors: "Thomas Townsley, John Carr, Matthew Lewis"
date: "December 7th, 2018""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
```

## R Markdown

This is the markdown file for our final project. 

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r}
# 1. Abstract. One parapgraph summary what we set out to learn and what final conclusions were. 
```



```{r}
# 2. Introduction. Discussion of the research and business in question. 
```


```{r}

# 3. Overview of the dataset

```


```{r}
# 4. Exploratory analysis

# TIPS from Prof. Stevens: use barplots for categorical variables 
# Use GGalley package to expand ggplot2. Includes histogram and correlation pair plotting functions

library(GGally) #if there's trouble installing the package, go to tools -> global options -> packages -> change CRAN mirror to Oakridge,TN

ggpairs(houses)
houses <- read.csv("DC_properties_clean.csv")
View(houses)
print(levels(houses$CNDTN))
houses$CNDTN <- factor(houses$CNDTN, levels = c("Fair", "Average", "Good", "Very Good", "Excellent"))

#fit <- lm(data = houses, PRICE ~ BATHRM + HF_BATHRM + ROOMS + BEDRM + AYB + YR_RMDL + STORIES + GBA + LANDAREA)
fit <- lm(data = houses, PRICE ~ BATHRM + BEDRM + GBA + LANDAREA + CNDTN + SALEDATE)
summary(fit)




```


```{r}

# 5. Identification and evaluation of suitable model

```


```{r}

# 6. Application of the model 

```


```{r}

# 7. Limitations and assumptions 

```



